export { default as ReportsCogs } from './cogs/reportsCogs'
export { default as ManageIntrastat } from './manageIntrastat/manageIntrastat'
export { default as ReportsIntrastat } from './intrastat/reportsIntrastat'
export { default as ReportsPlasticTax } from './plasticTax/reportsPlasticTax'
export { default as ReportsSynthesis } from './synthesis/reportsSynthesis'
